apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/t3code.janpuc.com_extensions.yaml
  - bases/t3code.janpuc.com_harnesses.yaml
  - bases/t3code.janpuc.com_mcpservers.yaml
  - bases/t3code.janpuc.com_workstations.yaml
